// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/AleksandrMatsko/cloudru-balancer/internal/health (interfaces: Observer)
//
// Generated by this command:
//
//	mockgen -destination=internal/health/mocks/observer.go -package=mock_observer github.com/AleksandrMatsko/cloudru-balancer/internal/health Observer
//

// Package mock_observer is a generated GoMock package.
package mock_observer

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockObserver is a mock of Observer interface.
type MockObserver struct {
	ctrl     *gomock.Controller
	recorder *MockObserverMockRecorder
	isgomock struct{}
}

// MockObserverMockRecorder is the mock recorder for MockObserver.
type MockObserverMockRecorder struct {
	mock *MockObserver
}

// NewMockObserver creates a new mock instance.
func NewMockObserver(ctrl *gomock.Controller) *MockObserver {
	mock := &MockObserver{ctrl: ctrl}
	mock.recorder = &MockObserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockObserver) EXPECT() *MockObserverMockRecorder {
	return m.recorder
}

// UpdateBackendHealth mocks base method.
func (m *MockObserver) UpdateBackendHealth(backend string, heathy bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateBackendHealth", backend, heathy)
}

// UpdateBackendHealth indicates an expected call of UpdateBackendHealth.
func (mr *MockObserverMockRecorder) UpdateBackendHealth(backend, heathy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBackendHealth", reflect.TypeOf((*MockObserver)(nil).UpdateBackendHealth), backend, heathy)
}
